/var/log/nginx/*.log {
    daily
    size 500M
    rotate 7
    dateext
    dateformat -%Y-%m-%d
    compress
    delaycompress
    missingok
    notifempty
    sharedscripts
    postrotate
        test -r /run/nginx.pid && kill -USR1 $(cat /run/nginx.pid)
    endscript
}
