name: Sync Intel gprofiler-performance-studio

on:
  schedule:
    - cron: '0 5 * * 1' # Mondays at 5am UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pinterest/gprofiler-performance-studio
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Add Intel Remote
        run: git remote add intel https://github.com/intel/gprofiler-performance-studio.git

      - name: Fetch Intel
        run: git fetch intel

      - name: Create or Update sync branch
        run: |
          git checkout -B intel-sync
          git merge --no-ff intel/master || true

      - name: Push sync branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push -f origin intel-sync

      - name: Create or Update PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: intel-sync
          title: 'Sync from upstream Intel gprofiler-performance-studio'
          body: |
            Automated weekly sync from Intel's gprofiler-performance-studio repository.
            Please review, resolve conflicts (if any), and approve to merge into main.
          base: master

